enable-magisk-update = true

[YT Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
#version = "6.29.58"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
included-patches = "'Background play' 'Bitrate default value' 'Certificate spoof' 'Custom playback speed' 'Enable force minimized player' 'Enable landscape mode' 'Enable minimized playback' 'Enable new player background' 'Enable opus codec' 'Enable playback speed' 'Enable sleep timer' 'Exclusive audio playback' 'Hide general ads' 'Hide get premium' 'Hide navigation bar component' 'Hook download button' 'Return YouTube Dislike' 'Sanitize sharing links' 'Settings' 'SponsorBlock' 'Spoof app version'"
exclusive-patches = true


[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
#version = "18.45.43"
excluded-patches = "'Alternative thumbnails' 'Wide searchbar' 'Hide captions button' 'Hide cast button' 'Hide player buttons' 'Disable player popup panels' 'Custom player overlay opacity' 'Disable auto captions' 'Hide timestamp' 'Hide layout components' 'Hide endscreen cards' 'Hide album cards' 'Hide email address' 'Hide breaking news shelf' 'Hide filter bar' 'Hide 'Load more' button' 'Disable suggested video end screen' 'Hide seekbar' 'Comments' 'Spoof app version' 'Enable tablet layout' 'Tablet mini player' 'Always autorepeat' 'Announcements' 'Enable debugging' 'Swipe controls' 'Enable slide to seek'"
