enable-magisk-update = true

[YT Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
version = "6.37.50"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
included-patches = "'Background play' 'Bitrate default value' 'Certificate spoof' 'Custom package name' 'Custom playback speed' 'Enable force minimized player' 'Enable landscape mode' 'Enable minimized playback' 'Enable opus codec' 'Enable playback speed' 'Exclusive audio playback' 'Hide action bar component' 'Hide fullscreen share button' 'Hide general ads' 'Hide get premium' 'Hide navigation bar component' 'MicroG support' 'Return YouTube Dislike' 'Sanitize sharing links' 'Settings' 'SponsorBlock'"
exclusive-patches = true


[YouTube]
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
# apkmirror-arch = "arm64-v8a"
# build-mode = "both"
# #version = "18.46.43"
# excluded-patches = "'Alternative thumbnails' 'GmsCore support' 'Wide searchbar' 'Hide captions button' 'Hide cast button' 'Hide player buttons' 'Disable player popup panels' 'Custom player overlay opacity' 'Disable auto captions' 'Hide timestamp' 'Hide layout components' 'Hide endscreen cards' 'Hide album cards' 'Hide email address' 'Hide breaking news shelf' 'Hide filter bar' 'Hide 'Load more' button' 'Disable suggested video end screen' 'Hide seekbar' 'Comments' 'Spoof app version' 'Enable tablet layout' 'Tablet mini player' 'Always autorepeat' 'Announcements' 'Enable debugging' 'Swipe controls' 'Enable slide to seek'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
included-patches = "'Ambient mode switch' 'Custom package name' 'Custom playback speed' 'Default video quality' 'Disable haptic feedback' 'Disable shorts on startup' 'Enable external browser' 'Enable minimized playback' 'Enable new thumbnail preview' 'Enable old quality layout' 'Enable open links directly' 'Enable seekbar tapping' 'Enable song search' 'Force OPUS codec' 'Force video codec' 'Hide autoplay button' 'Hide autoplay preview' 'Hide button container' 'Hide cast button' 'Hide channel watermark' 'Hide crowdfunding box' 'Hide end screen cards' 'Hide floating microphone' 'Hide general ads' 'Hide info cards' 'Hide latest videos button' 'Hide layout components' 'Hide navigation buttons' 'Hide previous next button' 'Hide shorts components' 'Hide suggested video overlay' 'Hide video ads' 'MicroG support' 'Overlay buttons' 'Premium heading' 'Return YouTube Dislike' 'Sanitize sharing links' 'Settings' 'SponsorBlock' 'Spoof app version' 'Spoof device dimensions' 'Spoof player parameters' 'Theme'"
exclusive-patches = true
